<?php

/**
 * Implements hook_module_theme_override().
 */
function Tabs_module_theme_override() {
  return array(
    array(
      'base hook' => 'menu_local_tasks',
    ),
    array(
      'base hook' => 'menu_local_task',
    )
  );
}

function Tabs_menu_local_tasks(&$variables) {
  $output = '';

  if (!empty($variables['primary'])) {
    foreach($variables['primary'] as $key => $link){
      if(isset($variables['primary'][$key]['#link']['localized_options'])) {
        $variables['primary'][$key]['#link']['localized_options']['attributes']['class'][] = 'Tabs-tab-link';
      }
    }
    $variables['primary']['#prefix'] = '<h2 class="u-hiddenVisually">' . t('Primary tabs') . '</h2>';
    $variables['primary']['#prefix'] .= '<ul class="Tabs u-cf">';
    $variables['primary']['#suffix'] = '</ul>';
    $output .= drupal_render($variables['primary']);
  }
  if (!empty($variables['secondary'])) {
    $variables['secondary']['#prefix'] = '<h2 class="u-hiddenVisually">' . t('Secondary tabs') . '</h2>';
    $variables['secondary']['#prefix'] .= '<ul class="Tabs u-cf">';
    $variables['secondary']['#suffix'] = '</ul>';
    $output .= drupal_render($variables['secondary']);
  }

  return $output;
}

function Tabs_menu_local_task($variables) {
  $link = $variables['element']['#link'];
  $link_text = $link['title'];

  if (!empty($variables['element']['#active'])) {
    // Add text to indicate active tab for non-visual users.
    $active = '<span class="u-hiddenVisually">' . t('(active tab)') . '</span>';

    // If the link does not contain HTML already, check_plain() it now.
    // After we set 'html'=TRUE the link will not be sanitized by l().
    if (empty($link['localized_options']['html'])) {
      $link['title'] = check_plain($link['title']);
    }
    $link['localized_options']['html'] = TRUE;
    $link_text = t('!local-task-title!active', array('!local-task-title' => $link['title'], '!active' => $active));
  }

  $task_attributes = array();
  $task_attributes['class'][] = 'Tabs-tab';
  if(!empty($variables['element']['#active'])) {
    $task_attributes['class'][] = 'is-active';
  }

  return '<li' . drupal_attributes($task_attributes) . '>' . l($link_text, $link['href'], $link['localized_options']) . "</li>\n";
}